# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d46d8f2b48c70f85f83ac6a5512158723bb345d869585fdf4bfe08f08db3304848f592363bba6672e2f1dd526904e27a4bfc599e76ae59fba1b81f454061f75d

test:
  secret_key_base: 9b109b52eac633efaa94888e48a2fd6363a44188b0a4276217a1a240fae25018a5e093193bb70e00ccb7e9e3af4dfcf8361685bd122d6730ede5480b47c8d0ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
